"""Fixed protocol constants for the DreamZero/LIBERO route."""

ACTION_OVERLAP_COORDINATES = 8 * 7
STATE_SLOT_COORDINATES = 48 * 10 * 20
DEFAULT_STATE_WEIGHT = (
    ACTION_OVERLAP_COORDINATES / STATE_SLOT_COORDINATES
) ** 0.5
